version: "3.9"

services:
  # Toolbox
  termproject:
    build: .
    environment:
      - DISPLAY=10.95.32.75:0.0
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - .:/root/working
    image: modabo/termproject2
  # RStudio
  rstudio:
    environment:
      - DISABLE_AUTH=true
    image: rocker/rstudio
    ports:
      - 8787:8787

  # Spyder
  spyder:
    image: compdatasci/spyder-desktop
    ports:
      - 6080:6080

  # IBM SAS

  # Git
  git:
    image: bitnami/git
    container_name: Git
    ports:
      - 7272:7272
    tty: true
  
  # Jupyter Notebook
  jupyter:
    image: jupyter/minimal-notebook
    environment:
      - JUPYTER_TOKEN=easy
    ports:
      - 8889:8889
    command: jupyter notebook --allow-root --ip='0.0.0.0' --port=8889 --no-browser --NotebookApp.token='' --NotebookApp.password=''

  # Orange
  orange:
    image: acopar/orange-docker
    environment: 
      - DISABLE_AUTH=true
    ports:
      - 6901:6901

  #Visual Studio Code
  vscode:
    image: linuxserver/code-server
    ports:
      - 8443:8443

  # Apache Hadoop

  # Apache Spark
  spark:
    image: jupyter/all-spark-notebook
    container_name: spark
    ports:
      - "8080:8080"
    command: jupyter notebook --allow-root --ip='0.0.0.0' --port=8080 --no-browser --NotebookApp.token='' --NotebookApp.password=''

  # Tableau
  tableau:
    image: pvtmert/tableau
    ports:
      - 8316:8316
  
  # SonarQube & SonarScanner (or SonarCloud)
  
  # Tensorflow
  tensorflow:
    image: tensorflow/tensorflow:latest-jupyter
    ports:
      - 8989:8888
    environment:
      - JUPYTER_TOKEN=password
  # Markdown
  markdown-server:
    image: v4tech/markdown-editor
    ports:
      - 12345:80